BOIL VEGETABLE, 0x41
BOIL PROTEIN, 0x42
GRIND PROTEIN, VEGETABLE
SPELL 1
ROAST PROTEIN, PROTEIN
ROAST VEGETABLE, VEGETABLE
GOODBYE VEGETABLE, PROTEIN
ROAST PROTEIN, PROTEIN
ROAST VEGETABLE, VEGETABLE
