BOIL CARBO, 0x00
WINDOW PROTEIN
WINDOW CARBO
WINDOW MEAT
WINDOW FRUIT
WINDOW DAIRY
WINDOW VEGETABLE
SPELL 1
ROAST PROTEIN, PROTEIN
ROAST CARBO, CARBO
ROAST MEAT, MEAT
ROAST FRUIT, FRUIT
ROAST DAIRY, DAIRY
ROAST VEGETABLE, VEGETABLE
