BOIL CARBO, 0x00
WINDOW MEAT
BOIL CARBO, 0x01
WINDOW FRUIT
QUICKMAFFS 0x00
GOODBYE MEAT, PROTEIN
QUICKMAFFS 0x01
GOODBYE FRUIT, PROTEIN
BOIL CARBO, 0x42
QUICKMAFFS 0x00
WINDOW PROTEIN
LADDER CARBO
QUICKMAFFS 0x01
WINDOW PROTEIN
CHAIR
BOIL PROTEIN, 0x42
BOIL CARBO, 0x70
PEPEFROG PROTEIN, CARBO
